### ISSUE TITLE
README link 404 Non Found for [Auto Update Support project](https://github.com/VSCodium/vscodium/projects/1)

### ISSUE THREAD

**Issue by paulvi** [VSCodium/update-api#9]
README link 404 Non Found for [Auto Update Support project](https://github.com/VSCodium/vscodium/projects/1)

> A small server that VSCodium calls to check for the latest release on GitHub. See the [Auto Update Support project](https://github.com/VSCodium/vscodium/projects/1) and the [original issue](https://github.com/VSCodium/vscodium/issues/41) for more context.

**Comment by daiyam** [comment]
The auto-update is working correctly for the system which are using it.
If you have used a package manager to install, please use that package manager to update.

If you have any problem, please open an issue at https://github.com/VSCodium/vscodium
